# ---------------------------------------------------------------- #
# CodeRabbit 기본 설정 (언어 및 페르소나)
# ---------------------------------------------------------------- #
language: 'ko-KR'

# 페르소나와 응답 톤앤매너 지시 (최대 250자)
tone_instructions: >
  프론트엔드 코치입니다. 코드 품질을 높이도록 돕는 것이 목표.
  1) 피드백은 명확하고 구체적이며 원인과 개선안을 함께 제시
  2) 가독성, 안정성(예외 처리), 테스트, 유지보수, 확장성 관점 중심으로 제시
  3) 접근성, 브라우저 호환성도 반드시 점검
  4) 공식 문서를 기반으로 제시

# ---------------------------------------------------------------- #
# 코드 리뷰 기능 세부 설정
# ---------------------------------------------------------------- #
reviews:
  profile: 'chill' # 리뷰 톤
  request_changes_workflow: false # 모든 코멘트 resolve 시 자동 Approve
  high_level_summary: true # PR 전체 요약
  changed_files_summary: false # 파일 단위 요약
  sequence_diagrams: false # 시퀀스 다이어그램
  poem: false # 리뷰 요약에 시 포함
  assess_linked_issues: true # 연결된 이슈 분석
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false

  path_instructions:
    - path: '**'
      instructions: |
        1. **높은 코드 품질**인지 철저히 확인하고 변수 네이밍도 점검
        2. 새로운 기능 추가나 수정 시, 기존 코드와의 호환성, 재사용성뿐 아니라 **확장 가능한 구조**인지도 검토
        3. Next.js/TypeScript 최신 베스트 프랙티스를 우선 적용
        4. 가독성과 안정성(에러/예외 처리)을 최우선으로 검토하고, 로직이 단순하고 직관적으로 읽히는지 확인
        5. 단위 테스트/통합 테스트가 충분히 작성되어 있는지, 테스트하기 쉬운 구조인지 검토
        6. 브라우저/디바이스 호환성과 접근성(ARIA, 키보드 내비게이션 등) 문제가 없는지 확인
        7. 복잡한 비즈니스 로직, 훅, 상태 관리 등은 후속 개발자가 쉽게 이해할 수 있도록 JSDoc이나 간단한 주석을 권장
        8. 리뷰 포인트는 문제점, 대안, 장단점을 논리적으로 제시하고, 필요 시 예시 코드도 포함
        9. 리뷰는 꼭 필요한 부분에 집중하되, 전체 맥락 이해를 돕기 위해 추가 설명은 캡션이나 요약으로 제공

  auto_review:
    enabled: true # PR 생성 시 자동 리뷰
    auto_incremental_review: true # 새 커밋 시 변경 부분만 리뷰

tools:
  gitleaks:
    enabled: true
  yamllint:
    enabled: true
  markdownlint:
    enabled: true

# ---------------------------------------------------------------- #
# 채팅 기능 세부 설정
# ---------------------------------------------------------------- #
chat:
  auto_reply: false # @coderabbitai 태그 없이도 자동 답글

# ---------------------------------------------------------------- #
# Knowledge Base 세부 설정
# ---------------------------------------------------------------- #
knowledge_base:
  web_search:
    enabled: true
  code_guidelines:
    enabled: false
  learnings:
    scope: 'local'
  issues:
    scope: 'local'
  pull_requests:
    scope: 'local'
